dist: xenial
language: cpp 
addons:
  apt:
    packages:
      - doxygen
        
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile

deploy:
- provider: script
  skip_cleanup: true
  script:
  - curl --fail -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uivan-krivosheev:$BINTRAY_API_KEY "https://api.bintray.com/content/ivan-krivosheev/otus-cpp/print-ip/$TRAVIS_BUILD_NUMBER/print-ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
- provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  repo: ikrivosheev/ikrivosheev.githab.io
  local_dir: doxygen/html
  target-branch: master
  on:
    branch: master
